### ISSUE TITLE
Install and config translations 

### ISSUE THREAD

**Issue by ehdlg** [Sergih28/groc#14]
### Description

Install and config:

- ~react-18next~
- [x] Translations

Translations will not be automatically generated, we will rely on DeepL, google translate and ChatGPT, as decided in #25.

This is the list of languages that the project should have when setting this up:

- [x] English (the default one)
- [x] Spanish
- [x] Catalan
- [x] Korean
- [x] Japanese

**Comment by Sergih28** [comment]
@ehdlg You can continue implementing the other 2 languages.

Some tests might be broken, and there are some other compilation errors that prevented the push without `--no-verify`, so I'd be great if you could address those things as well.
