### ISSUE TITLE
Decide which global state library to use

### ISSUE THREAD

**Issue by Sergih28** [Sergih28/groc#23]
Decide which react global state library to use.

The main candidates are:

- [Legend](https://legendapp.com/open-source/state/intro/introduction/)
- [Zustand](https://zustand-demo.pmnd.rs/)

**Comment by Sergih28** [comment]
@ehdlg Could you please investigate about both libraries (or other ones if you feel they should be candidates), and put a list of pros and cons of using each library? 😄 

This way we can make a more concius decision of using one or the other one 😃.

You can add the list as a reply on this issue 👌.

**Comment by ehdlg** [comment]
@Sergih28  I'm leaning towards Zustand as the better option due to its strong community support, ease of use, and simplicity compared to Legend.
