### ISSUE TITLE
Look for a way to add autogenerated translations in React

### ISSUE THREAD

**Issue by Sergih28** [Sergih28/groc#25]
Look if there is a free way to integrate autogenerated translations with React i18next.

**Comment by Sergih28** [comment]
@ehdlg Please post here the required information you find to solve this issue 😃.

**Comment by Sergih28** [comment]
I've done some research and I barely found anything, just one library that needs a google api key, which I'm not a fan of.


So I think the best way would be to do the translations ourselves and use [Deepl](https://www.deepl.com/translator) and ChatGPT to translate the strings.

What do you think @ehdlg?

**Comment by ehdlg** [comment]
> I've done some research and I barely found anything, just one library that needs a google api key, which I'm not a fan of.
> 
> So I think the best way would be to do the translations ourselves and use [Deepl](https://www.deepl.com/translator) and ChatGPT to translate the strings.
> 
> What do you think @ehdlg?

Sounds good, I think relying on DeepL and ChatGPT for our translations is the way to go.

**Comment by Sergih28** [comment]
Closing this, as the changes will take place in #24.
