### ISSUE TITLE
Decide what js date library to use

### ISSUE THREAD

**Issue by Sergih28** [Sergih28/groc#35]
A decision has to be made regarding what js date library to use, as I think it will be useful when doing calculations with dates.

**Comment by Sergih28** [comment]
@ehdlg Could you please take a look of what js date libraries are out there and what are the one/s you think it would be more useful to use in the project?

Preferably, I'd like it to not be a very heavy library, as it will mainly be used to calculate the time from one date to another.

And the ease of use is something to keep in mind as well.

**Comment by ehdlg** [comment]
@Sergih28 
Among the date libraries that I found, Day.js, Date-fns, and Moment.js are prominent choices.

- Day.js stands out for its small size and modular nature, allowing tailored feature selection to prevent unnecessary bloat. Its minimalist API mirrors Moment.js in ease of use.

- Date-fns offers over 200 functions, supporting modularity, tree-shaking, and compatibility with TypeScript.

- In contrast, Moment.js, although comprehensive and popular, tends to be heavier.

Considering the project's focus on avoiding bloat and prioritizing essential features, Day.js emerges as the right choice in my opinion.

**Comment by Sergih28** [comment]
Sounds good to me :+1: 

@ehdlg Could you add a new decision file for this?

**Comment by Sergih28** [comment]
@ehdlg Install dayjs library.

(Remove the "^" from all the libraries installed in package json please)
