### ISSUE TITLE
Propose a json structure to save the pomodoro data (in localstorage)

### ISSUE THREAD

**Issue by Sergih28** [Sergih28/groc#66]
Keep in mind that you have to know when you start and finish in terms of datetimes, but you can have pauses in between.

Feel free to write the example with invented data to see the json structure.

**Comment by ehdlg** [comment]
Here is my proposal for the JSON structure:

The JSON contains a key with an array named "pomodoros". Each element in this array represents a pomodoro and is an object that includes:

- id: A unique identifier for the pomodoro. 
- startTime: A string indicating the start time of the pomodoro.
- endTime: A string indicating the end time of the pomodoro.
- pausedTime: An array of objects representing the start and end of each pause within the pomodoro. If there are no pauses, this array will be empty ([]). Each object within this array contains the start and end of a pause.

The start and end time are represented as Unix timestamps, but these values can be altered.

Here's the JSON example:

```
{
  "pomodoros": [
    {
      "id": "unique_id_1",
      "startTime": 1636958400, 
      "endTime": 1636960500, 
      "pausedTime": [
        {
          "start": 1636958700, 
          "end": 1636959000 
        },
        {
          "start": 1636959300, 
          "end": 1636959600 
        }
      ]
    },
    {
      "id": "unique_id_2",
      "startTime": 1637045400,
      "endTime": 1637047500,
      "pausedTime": []
    }
  ]
}

```

**Comment by ehdlg** [comment]
Got it, here is the JSON with the changes that you proposed:

```
{
  "pomodoros": [
    {
      "id": unique_uuid,
      "startTime": 1636958400, 
      "endTime": 1636960500, 
      "pausedTimeRanges": [
        {
          "start": 1636958700, 
          "end": 1636959000 
        },
        {
          "start": 1636959300, 
          "end": 1636959600 
        }
      ]
    },
    {
      "id": unique_uuid,
      "startTime": 1637045400,
      "endTime": 1637047500,
      "pausedTimeRanges": []
    }
  ]
}


```

Regarding the file name and the location, I think 'pomodoroSampleData.json' could be a good name, and for the location, placing it in a designated 'data' folder within the 'src' directory offers a logical and organized structure.
